blank_issues_enabled: false
contact_links:
  - name: Community Forum on GitHub
    url: https://github.com/scikit-learn/scikit-learn/discussions
    about: For Q&A, issues, general discussion.
  - name: Questions tagged 'scikit-optimize' on StackOverflow
    url: https://stackoverflow.com/questions/tagged/scikit-optimize
    about: For skopt-related programming questions with a wide audience.
